templateDir: ./sdk-resources/resources
packageName: PSSailpoint.Beta
packageVersion: 1.7.2
apiNamePrefix: Beta
apiVersion: beta
companyName: SailPoint Technologies
packageGuid: 61785CF2-2EB2-4FB6-9F7C-C5BD5B1733E8
commonVerbs: Delete=Remove:Cancel=Suspend:Patch=Update:List=Get:Query=Search:Run=Start:Validate=Confirm:Make=Select
discardReadOnly: true
subModuleName: Beta
functionPrefix: Beta
files:
  developerSite_code_examples.mustache:
    templateType: APIDocs
    destinationFilename: developerSite_code_examples.yaml
  docs_methods_index.mustache:
    templateType: SupportingFiles
    destinationFilename: docs/Methods/Index.md
  docs_models_index.mustache:
    templateType: SupportingFiles
    destinationFilename: Index.md
