templateDir: ./sdk-resources/resources
packageName: PSSailpoint.V2026
packageVersion: 1.7.4
apiNamePrefix: V2026
apiVersion: v2026
companyName: SailPoint Technologies
packageGuid: D4B8E3C3-1F7C-4D1C-8A2E-3F6C2E5B9A12
commonVerbs: Delete=Remove:Cancel=Suspend:Patch=Update:List=Get:Query=Search:Run=Start:Validate=Confirm:Make=Select
discardReadOnly: true
subModuleName: V2026
functionPrefix: V2026
files:
  developerSite_code_examples.mustache:
    templateType: APIDocs
    destinationFilename: developerSite_code_examples.yaml
  docs_methods_index.mustache:
    templateType: SupportingFiles
    destinationFilename: docs/Methods/Index.md
  docs_models_index.mustache:
    templateType: SupportingFiles
    destinationFilename: Index.md
