templateDir: ./sdk-resources/resources
packageName: PSSailpoint.V3
packageVersion: 1.7.14
apiVersion: v3
companyName: SailPoint Technologies
packageGuid: 7A197170-97E8-4DCD-A171-271D4AEC2F34
commonVerbs: Delete=Remove:Cancel=Suspend:Patch=Update:List=Get:Query=Search:Run=Start:Validate=Confirm:Make=Select
discardReadOnly: true
subModuleName: V3
functionPrefix:
files:
  developerSite_code_examples.mustache:
    templateType: APIDocs
    destinationFilename: developerSite_code_examples.yaml
  docs_methods_index.mustache:
    templateType: SupportingFiles
    destinationFilename: docs/Methods/Index.md
  docs_models_index.mustache:
    templateType: SupportingFiles
    destinationFilename: Index.md
